# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  mavenRepoURL: 'https://bithaus.pkgs.visualstudio.com/_packaging/medium_artifact/maven/v1'

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: mvnSettings
  displayName: 'Download Maven settings'
  inputs:
    secureFile: 'maven-azuredevops-settings.xml'
- task: MavenAuthenticate@0
  displayName: Maven Authenticate Artifacts
  inputs:
    artifactsFeeds: 'medium_artifact'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom-devop.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    options: '-X -B -s $(mvnSettings.secureFilePath)  -DremoteRepositories=$(mavenRepoUrl) clean deploy -U'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'
#- task: CopyFiles@2
#  inputs:
#    contents: 'target/bithaus-medium-1.0.jar'
#    targetFolder: '$(Build.ArtifactStagingDirectory)'
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'bithausmedium'
#    publishLocation: 'Container'
